### ISSUE TITLE
Importing does not work

### ISSUE THREAD

**Issue by ernestqt** [Hart-House-Chess-Club/fen-to-image#2]
I pip installed the library as recommended: `pip install fentoimage`.

However, after that I tried `from fentoimage.board import BoardImage` and I get 

> .. /lib/python3.11/site-packages/fentoimage/config.py:33
>      28     @property
>      29     def color(self):
>      30         return (self.light_color, self.dark_color)
> ---> 33 @dataclass
>      34 class Config:
>      35      inkscape_location: str = "inkscape"
>      36      piece_theme: str = "cburnett"
> 
> ValueError: mutable default  for field square is not allowed: use default_factory.

Just in case, I am using an M1 Mac.

**Comment by zzhang-qppi** [comment]
Same error here

**Comment by vzcodes** [comment]
@ahmedkhalf , can you take a look at this? A pull request has also been made. 

I'm running windows and cannot reproduce this error.
